--- #YAML:1.0
name:                File-Value
version:             0.20
abstract:            manipulate file name or content as a single value
license:             BSD
author:              
    - John A. Kunze <jak@ucop.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Fcntl:                         0
    File::Copy:                    0
    File::Glob:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
