--- #YAML:1.0
name:               File-Value
version:            v0.2.4
abstract:           snag (command) and routines supporting files as values
author:
    - John A. Kunze <jak@ucop.edu>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fcntl:         0
    File::Copy:    0
    File::Glob:    0
    Getopt::Long:  0
    Pod::Usage:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
